var GRAMMAR_STORY_MAP = {
  "G01":{"title":"Be동사 현재형","level":"A1","example":"I am a student. She is happy. They are friends.","prompt":"저는 G01 Be동사 현재형을 공부 중이에요. am/is/are 사용법을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G02":{"title":"관사 a/an/the","level":"A1","example":"I have a cat. She ate an apple. The sun is bright.","prompt":"저는 G02 관사를 공부 중이에요. a/an/the 차이를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G03":{"title":"단순현재시제","level":"A1","example":"He plays soccer every day. She likes coffee.","prompt":"저는 G03 단순현재를 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G04":{"title":"현재진행형","level":"A1","example":"I am studying English now. She is cooking dinner.","prompt":"저는 G04 현재진행형을 공부 중이에요. am/is/are+-ing를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G05":{"title":"단순과거시제","level":"A1","example":"I visited Seoul last week. She played piano yesterday.","prompt":"저는 G05 단순과거를 공부 중이에요. 규칙/불규칙 과거형을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G06":{"title":"미래시제 will/going to","level":"A1","example":"I will call you later. She is going to study abroad.","prompt":"저는 G06 미래시제를 공부 중이에요. will과 going to 차이를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G07":{"title":"조동사 can/could/should","level":"A1","example":"I can swim. You should study hard. Could you help me?","prompt":"저는 G07 조동사를 공부 중이에요. can/could/should를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G08":{"title":"가산/불가산 명사","level":"A1","example":"I need some water and two apples. There is much information.","prompt":"저는 G08 가산/불가산 명사를 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G09":{"title":"의문문 만들기","level":"A1","example":"Where do you live? What did you eat for lunch?","prompt":"저는 G09 Wh-의문문을 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G10":{"title":"비교급/최상급","level":"A1","example":"She is taller than me. He is the smartest student.","prompt":"저는 G10 비교급/최상급을 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G11":{"title":"소유격 표현","level":"A1","example":"This is my book. That is John's bag. Its color is blue.","prompt":"저는 G11 소유격을 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G12":{"title":"There is/There are","level":"A1","example":"There is a cat on the roof. There are many students.","prompt":"저는 G12 There is/are를 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G13":{"title":"장소 전치사","level":"A1","example":"The book is on the table. She lives in Seoul.","prompt":"저는 G13 장소 전치사를 공부 중이에요. in/on/at을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G14":{"title":"시간 전치사","level":"A1","example":"I study at 8 AM. She was born in May. We meet on Friday.","prompt":"저는 G14 시간 전치사를 공부 중이에요. in/on/at을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G15":{"title":"지시대명사","level":"A1","example":"This is mine. Those are yours. That book is interesting.","prompt":"저는 G15 지시대명사를 공부 중이에요. this/that/these/those를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G16":{"title":"복수명사","level":"A1","example":"One child, two children. One tooth, many teeth.","prompt":"저는 G16 복수명사를 공부 중이에요. 규칙/불규칙 복수를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G17":{"title":"목적격 대명사","level":"A1","example":"Give it to me. I saw him yesterday. She told us a story.","prompt":"저는 G17 목적격 대명사를 공부 중이에요. me/you/him/her를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G18":{"title":"Yes/No 의문문","level":"A1","example":"Do you like pizza? Yes, I do. Is she coming? No, she isn't.","prompt":"저는 G18 Yes/No 의문문을 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G19":{"title":"빈도부사","level":"A1","example":"I always eat breakfast. She never drinks coffee.","prompt":"저는 G19 빈도부사를 공부 중이에요. always/often/sometimes/never를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G20":{"title":"명령문","level":"A1","example":"Open the door! Don't be late! Please sit down.","prompt":"저는 G20 명령문을 공부 중이에요. 긍정/부정 명령문을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G21":{"title":"과거진행형","level":"A2","example":"I was reading when she called. They were playing outside.","prompt":"저는 G21 과거진행형을 공부 중이에요. was/were+-ing를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G22":{"title":"현재완료","level":"A2","example":"I have lived here for 10 years. She has visited Paris twice.","prompt":"저는 G22 현재완료를 공부 중이에요. have/has+p.p.를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G23":{"title":"Must/Have to/Need to","level":"A2","example":"You must wear a seatbelt. I have to finish this report.","prompt":"저는 G23 의무 표현을 공부 중이에요. must/have to/need to를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G24":{"title":"Some/Any/No/None","level":"A2","example":"I have some money. Do you have any questions? There is no time.","prompt":"저는 G24 some/any/no를 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G25":{"title":"방법부사","level":"A2","example":"She sings beautifully. He drives carefully. They work hard.","prompt":"저는 G25 방법부사를 공부 중이에요. -ly 부사를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G26":{"title":"접속사 and/but/or/so","level":"A2","example":"I like tea but she likes coffee. Study hard, or you will fail.","prompt":"저는 G26 접속사를 공부 중이에요. and/but/or/so를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G27":{"title":"Like vs Would like","level":"A2","example":"I like pizza. I would like a cup of coffee, please.","prompt":"저는 G27 like vs would like를 공부 중이에요. 차이를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G28":{"title":"Too vs Enough","level":"A2","example":"It is too hot. She is old enough to drive.","prompt":"저는 G28 too/enough를 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G29":{"title":"1형식 조건문","level":"A2","example":"If it rains, I will stay home. If you study, you will pass.","prompt":"저는 G29 1형식 조건문을 공부 중이에요. If+현재,will을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G30":{"title":"동명사/부정사","level":"A2","example":"I enjoy reading. She decided to leave early.","prompt":"저는 G30 동명사/부정사를 공부 중이에요. 차이점을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G31":{"title":"관계대명사","level":"A2","example":"The man who helped me is kind. The book which I read was great.","prompt":"저는 G31 관계대명사를 공부 중이에요. who/which/that을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G32":{"title":"과거단순 vs 과거진행","level":"A2","example":"I was walking when it started to rain. She called while I was cooking.","prompt":"저는 G32 과거단순vs과거진행을 공부 중이에요. 차이를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G33":{"title":"Used to","level":"A2","example":"I used to live in Busan. She used to play tennis every day.","prompt":"저는 G33 used to를 공부 중이에요. 과거 습관을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G34":{"title":"부가의문문","level":"A2","example":"You like coffee, don't you? She is coming, isn't she?","prompt":"저는 G34 부가의문문을 공부 중이에요. question tag를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G35":{"title":"재귀대명사","level":"A2","example":"He hurt himself. She did it herself. I taught myself.","prompt":"저는 G35 재귀대명사를 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G36":{"title":"Each vs Every","level":"A2","example":"Each student has a book. Every child needs love.","prompt":"저는 G36 each vs every를 공부 중이에요. 차이를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G37":{"title":"Both/Either/Neither","level":"A2","example":"Both of them are smart. Neither answer is correct.","prompt":"저는 G37 both/either/neither를 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G38":{"title":"So vs Such","level":"A2","example":"It was such a great movie. She is so kind and generous.","prompt":"저는 G38 so/such를 공부 중이에요. 차이를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G39":{"title":"Still/Yet/Already","level":"A2","example":"He still lives here. Have you finished yet? I have already eaten.","prompt":"저는 G39 still/yet/already를 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G40":{"title":"직접/간접화법","level":"A2","example":"She said, 'I am tired.' → She said she was tired.","prompt":"저는 G40 직접/간접화법을 공부 중이에요. 변환 규칙을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G41":{"title":"현재완료 vs 과거단순","level":"B1","example":"I have been to Japan. I went to Japan last year.","prompt":"저는 G41 현재완료vs과거단순을 공부 중이에요. 차이를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G42":{"title":"현재완료진행형","level":"B1","example":"She has been waiting for an hour. I have been studying all day.","prompt":"저는 G42 현재완료진행형을 공부 중이에요. have been+-ing를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G43":{"title":"과거완료","level":"B1","example":"She had left before I arrived. I had never seen snow before that.","prompt":"저는 G43 과거완료를 공부 중이에요. had+p.p.를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G44":{"title":"미래완료","level":"B1","example":"By next year, I will have graduated. She will have finished by then.","prompt":"저는 G44 미래완료를 공부 중이에요. will have+p.p.를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G45":{"title":"가능성 조동사","level":"B1","example":"It might rain today. She could be at home. He may come later.","prompt":"저는 G45 가능성 조동사를 공부 중이에요. might/may/could를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G46":{"title":"2형식 조건문","level":"B1","example":"If I were rich, I would travel the world. If she knew, she would help.","prompt":"저는 G46 2형식 조건문을 공부 중이에요. If+과거,would를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G47":{"title":"3형식 조건문","level":"B1","example":"If she had studied, she would have passed the exam.","prompt":"저는 G47 3형식 조건문을 공부 중이에요. If+had p.p.,would have p.p.를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G48":{"title":"수동태","level":"B1","example":"The letter was written by Jane. English is spoken worldwide.","prompt":"저는 G48 수동태를 공부 중이에요. be+p.p. 구조를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G49":{"title":"사역동사","level":"B1","example":"She made him clean the room. I let her go early.","prompt":"저는 G49 사역동사를 공부 중이에요. make/let/have를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G50":{"title":"동명사/부정사 심화","level":"B1","example":"I stopped smoking. I stopped to smoke. (의미 차이)","prompt":"저는 G50 동명사/부정사 심화를 공부 중이에요. 의미 차이를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G51":{"title":"구동사","level":"B1","example":"I gave up smoking. She looked after the children. Turn off the light.","prompt":"저는 G51 구동사를 공부 중이에요. phrasal verb를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G52":{"title":"관계절","level":"B1","example":"The man who lives next door is a teacher. (한정적 관계절)","prompt":"저는 G52 관계절을 공부 중이에요. 한정적/비한정적을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G53":{"title":"간접화법","level":"B1","example":"He said he would come. She asked if I was free.","prompt":"저는 G53 간접화법을 공부 중이에요. 시제 변화를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G54":{"title":"Wish/If only","level":"B1","example":"I wish I could fly. If only I had more time.","prompt":"저는 G54 wish/if only를 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G55":{"title":"관사 심화","level":"B1","example":"The rich should help the poor. Life is beautiful. (무관사)","prompt":"저는 G55 관사 심화를 공부 중이에요. 고급 용법을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G56":{"title":"수량 표현","level":"B1","example":"Few students passed. There is little hope. Much work remains.","prompt":"저는 G56 수량 표현을 공부 중이에요. few/little/many/much를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G57":{"title":"연결어","level":"B1","example":"However, she kept trying. Therefore, he succeeded.","prompt":"저는 G57 연결어를 공부 중이에요. however/therefore/moreover를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G58":{"title":"강조 do/does/did","level":"B1","example":"I do believe you. She does love music. He did finish the work.","prompt":"저는 G58 강조 do를 공부 중이에요. do/does/did 강조를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G59":{"title":"분열문","level":"B1","example":"It was John that broke the window. What I need is sleep.","prompt":"저는 G59 분열문을 공부 중이에요. It is~that 구조를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G60":{"title":"혼합가정법","level":"B1","example":"If I had studied harder, I would be rich now.","prompt":"저는 G60 혼합가정법을 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G61":{"title":"과거 속 미래","level":"B1","example":"She was going to call you. I knew he would come.","prompt":"저는 G61 과거 속 미래를 공부 중이에요. was going to를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G62":{"title":"분사구문","level":"B1","example":"Sitting alone, she felt lonely. Having finished, he left.","prompt":"저는 G62 분사구문을 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G63":{"title":"도치구문","level":"B1","example":"Never have I seen such beauty. Rarely does he complain.","prompt":"저는 G63 도치구문을 공부 중이에요. 부정어 도치를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G64":{"title":"접속법","level":"B1","example":"I suggest that he study harder. It is essential that she be present.","prompt":"저는 G64 접속법을 공부 중이에요. subjunctive를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G65":{"title":"이중비교급","level":"B1","example":"The more you practice, the better you get.","prompt":"저는 G65 이중비교급을 공부 중이에요. the+비교급, the+비교급을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G66":{"title":"수동태 심화","level":"B1","example":"The bridge is being built. The report will have been completed.","prompt":"저는 G66 수동태 심화를 공부 중이에요. 다양한 시제 수동태를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G67":{"title":"추측 조동사","level":"B1","example":"She must have forgotten. He can't have been there.","prompt":"저는 G67 추측 조동사를 공부 중이에요. must have/can't have를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G68":{"title":"고급 조건문","level":"B1","example":"Unless you hurry, you will be late. Provided that you agree...","prompt":"저는 G68 고급 조건문을 공부 중이에요. unless/provided that을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G69":{"title":"명사절","level":"B1","example":"I know that she is right. Whether he comes is uncertain.","prompt":"저는 G69 명사절을 공부 중이에요. that/whether 명사절을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G70":{"title":"관계절 심화","level":"B1","example":"She passed, which surprised us. The reason why he left...","prompt":"저는 G70 관계절 심화를 공부 중이에요. 비한정적 관계절을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G71":{"title":"복합 구동사","level":"B1","example":"I came up with an idea. She looks forward to meeting you.","prompt":"저는 G71 복합 구동사를 공부 중이에요. 3단어 구동사를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G72":{"title":"간접화법 심화","level":"B1","example":"He told me not to worry. She asked where I had been.","prompt":"저는 G72 간접화법 심화를 공부 중이에요. 고급 변환을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G73":{"title":"생략/대용","level":"B1","example":"I can swim and she can too. He said he would, and he did.","prompt":"저는 G73 생략/대용을 공부 중이에요. ellipsis를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G74":{"title":"고급 연결어","level":"B1","example":"Furthermore, the data shows... In contrast, the results differ.","prompt":"저는 G74 고급 연결어를 공부 중이에요. furthermore/in contrast를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G75":{"title":"완화 표현","level":"B1","example":"It seems that... It appears to be... She tends to arrive late.","prompt":"저는 G75 완화 표현을 공부 중이에요. hedging을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G76":{"title":"전치/도치","level":"B1","example":"Only then did I realize. So beautiful was the sunset.","prompt":"저는 G76 전치/도치를 공부 중이에요. fronting을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G77":{"title":"복합 문장 구조","level":"B1","example":"Although tired, she continued working, which impressed everyone.","prompt":"저는 G77 복합 문장을 공부 중이에요. 복합 구조를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G78":{"title":"동명사/부정사 고급","level":"B1","example":"She is known to have written the book. Having been warned...","prompt":"저는 G78 동명사/부정사 고급을 공부 중이에요. 고급 용법을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G79":{"title":"명사화","level":"B1","example":"His arrival surprised us. The discovery of DNA changed science.","prompt":"저는 G79 명사화를 공부 중이에요. nominalization을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G80":{"title":"한정사 심화","level":"B1","example":"All the students passed. Each of the answers is correct.","prompt":"저는 G80 한정사 심화를 공부 중이에요. 고급 한정사를 예문 3개와 연습문제 2개로 설명해주세요!"}
};
