const fs=require('fs');
const tpl=fs.readFileSync(__dirname+'/ep01.html','utf8');
const cssM=tpl.match(/<style>([\s\S]*?)<\/style>/);
const CSS=cssM?cssM[1]:'';
const scrM=tpl.match(/<script>([\s\S]*?)<\/script>/);
const BASE_SCRIPT=`function getVoice(){var v=speechSynthesis.getVoices();var n=['Microsoft Zira Desktop - English (United States)','Samantha','Karen','Google US English'];for(var i=0;i<n.length;i++){var f=v.find(function(x){return x.name===n[i];});if(f)return f;}return v.find(function(x){return x.lang==='en-US';})||v[0];}
function speak(t){speechSynthesis.cancel();setTimeout(function(){var u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=0.8;u.pitch=1.0;var f=getVoice();if(f)u.voice=f;speechSynthesis.speak(u);},150);}`;

const D=[
["05",3,"02","Peter Rabbit","Beatrix Potter","1902","Don't go there!","garden,정원|danger,위험|gate,문|mother,엄마","엄마 토끼가 정원에 가지 말라고 경고해요.","Don't go into the garden.,정원에 들어가지 마.,Don't = Do not|It is very dangerous.,매우 위험해.,dangerous = 위험한|Mother said stay away.,멀리 있으라고 했어요.,stay away|Peter went through the gate.,문을 통과했어요.,went through|He did not listen.,듣지 않았어요.,did not","garden,가r든,r 혀를 뒤로|danger,데인저r,d 강하게|gate,게잇,t 살짝","mom,Peter don't go to the garden!,정원에 가지 마!|kid,Why not? I want to see!,왜요?|mom,It is dangerous there.,위험해.|kid,OK I will stay here.,알겠어요."],
["06",3,"03","Peter Rabbit","Beatrix Potter","1902","I am hungry!","hungry,배고픈|lettuce,상추|eat,먹다|big,큰","피터가 정원에서 상추를 먹기 시작해요!","Peter was very hungry.,매우 배가 고팠어요.,was hungry|He ate some lettuce.,상추를 먹었어요.,ate = eat 과거형|The garden had big vegetables.,큰 채소들이 있었어요.,vegetables = 채소들|I am so hungry!,너무 배고파!,so = 매우|He ate too much.,너무 많이 먹었어요.,too much","hungry,헝그리,h 강하게|lettuce,레티스,tt 가볍게|vegetables,베지터블즈,강세 첫째","mom,Peter are you hungry?,배고프니?|kid,Yes! I am very hungry!,배고파요!|mom,What do you want to eat?,뭐 먹을래?|kid,I want lettuce!,상추요!"],
["07",3,"04","Peter Rabbit","Beatrix Potter","1902","Stop! Come back!","stop,멈추다|back,돌아오다|chase,쫓다|farmer,농부","맥그리거 할아버지가 피터를 쫓아와요!","Mr. McGregor saw Peter!,할아버지가 피터를 봤어요!,saw = see 과거형|Stop! Come back!,멈춰! 돌아와!,명령문|Peter ran very fast.,매우 빠르게 달렸어요.,ran = run 과거형|The farmer chased Peter.,농부가 쫓았어요.,chased|Peter lost his shoes.,신발을 잃어버렸어요.,lost = lose 과거형","stop,스탑,p 강하게|chase,체이스,ch는 ㅊ|farmer,파r머r,r 두 번","mom,Stop! Come back!,멈춰!|kid,I'm sorry!,죄송해요!|mom,The farmer is coming!,농부가 와!|kid,Help!,도와줘요!"],
["08",3,"05","Peter Rabbit","Beatrix Potter","1902","I am scared!","hide,숨다|pot,화분|scared,무서운|find,찾다","피터가 화분 뒤에 숨어요!","Peter was very scared.,매우 무서웠어요.,was scared|He hid behind a pot.,화분 뒤에 숨었어요.,hid = hide 과거형|Can you find Peter?,찾을 수 있나요?,Can you|I am so scared!,너무 무서워!,so = 매우|Don't move! Stay quiet.,움직이지 마!,stay quiet","scared,스케어드,sc 빠르게|hide,하이드,h 내쉬며|quiet,콰이엇,2음절","mom,Peter where are you?,어디 있니?|kid,I am hiding!,숨어있어요!|mom,Don't worry.,걱정 마.|kid,I want to go home!,집에 가고 싶어요!"],
["09",3,"06","Peter Rabbit","Beatrix Potter","1902","Help me!","net,그물|button,단추|stuck,끼인|cry,울다","피터가 그물에 걸려 단추가 끼여요!","Peter got stuck in a net.,그물에 걸렸어요.,got stuck|His buttons were caught.,단추가 걸렸어요.,were caught|Help me! cried Peter.,도와줘!,cried = 울었다|He pulled and pulled.,당기고 또 당겼어요.,pulled|Finally he was free!,마침내 자유!,finally","button,버튼,tt 가볍게|stuck,스턱,ck 강하게|net,넷,짧게","mom,Oh no! Stuck!,이런!|kid,Help me!,도와줘요!|mom,Pull hard!,세게 당겨!|kid,I am free!,자유예요!"],
["10",3,"07","Peter Rabbit","Beatrix Potter","1902","Be quiet!","watering can,물뿌리개|quiet,조용한|breathe,숨쉬다|wait,기다리다","피터가 물뿌리개에 숨어요!","Peter hid in a watering can.,물뿌리개에 숨었어요.,hid in|Be quiet! Don't make a sound.,조용히 해!,Be quiet|Peter could not breathe.,숨을 쉴 수 없었어요.,could not|He had to wait.,기다려야 했어요.,had to|The water was very cold!,물이 차가웠어요!,cold","quiet,콰이엇,qu는 ㅋ와|breathe,브리드,th 혀 내밀어|watering,워터링,t 가볍게","mom,Shh! Be quiet!,쉿!|kid,I am trying!,노력 중이에요!|mom,Don't move.,움직이지 마.|kid,It's cold!,추워요!"],
["11",3,"08","Peter Rabbit","Beatrix Potter","1902","Run! Run fast!","run,달리다|fast,빠른|through,~을 통해|free,자유로운","피터가 빠르게 달려서 빠져나가요!","Peter ran as fast as he could.,최대한 빠르게 달렸어요.,as fast as|Run! Run fast!,뛰어! 빨리!,명령문|He ran through the garden.,정원을 가로질렀어요.,through|He found the gate!,문을 찾았어요!,found = find 과거형|Peter was free at last!,마침내 자유!,at last","through,쓰루,th 혀 내밀어|fast,패스트,a 길게|free,프리,r 주의","mom,Now! Run!,지금이야!|kid,I am running fast!,빨리 달려요!|mom,Go through the gate!,문으로!|kid,I am free!,자유예요!"],
["12",3,"09","Peter Rabbit","Beatrix Potter","1902","I am safe now.","safe,안전한|home,집|tired,피곤한|warm,따뜻한","피터가 집에 돌아와서 안전해요.","Peter was safe at home.,집에서 안전했어요.,was safe|I am safe now.,이제 안전해.,now = 이제|He was very tired.,매우 피곤했어요.,tired|Mother gave him warm tea.,엄마가 차를 줬어요.,gave = give 과거형|Peter went to bed.,잠자리에 들었어요.,went to bed","safe,세이프,f 살짝|tired,타이어드,2음절|warm,워r름,r 부드럽게","mom,You are home!,왔구나!|kid,I am safe now.,안전해요.|mom,You look tired.,피곤해 보여.|kid,Never again.,다시 안 갈 거예요."],
["13",4,"02","Wind in the Willows","Kenneth Grahame","1908","Hello friend!","river,강|boat,배|friend,친구|wave,손 흔들다","두더지 몰이 래티를 만나요!","Mole walked to the river.,강으로 걸어갔어요.,walked to|Hello friend! said Rat.,안녕 친구!,friend|Would you like a boat ride?,배 탈래?,Would you like|Mole waved hello.,손을 흔들었어요.,waved|They became good friends.,좋은 친구가 되었어요.,became","river,리버r,r 두 번|friend,프렌드,fr 빠르게|boat,보우트,oa는 오우","mom,Who is by the river?,강가에 누구?|kid,Hello friend!,안녕 친구!|mom,Want to ride my boat?,배 탈래?|kid,Yes! Let's go!,가요!"],
["14",4,"03","Wind in the Willows","Kenneth Grahame","1908","Let's go on a picnic!","picnic,소풍|basket,바구니|happy,행복한|together,함께","래티가 소풍을 제안해요!","Let's go on a picnic!,소풍 가자!,Let's|Rat packed a basket.,바구니를 쌌어요.,packed|They were so happy together.,함께 행복했어요.,together|The food was delicious.,맛있었어요.,delicious|What a wonderful day!,멋진 날!,What a = 감탄문","picnic,피크닉,c 두 번|basket,바스킷,a 짧게|together,투게더r,강세 두번째","mom,Let's have a picnic!,소풍 가자!|kid,I love picnics!,좋아요!|mom,I packed sandwiches.,샌드위치 싸왔어.|kid,Happy together!,함께 행복해요!"],
["15",4,"04","Wind in the Willows","Kenneth Grahame","1908","This is my house!","house,집|big,큰|proud,자랑스러운|visit,방문하다","토드가 큰 집을 자랑해요.","This is my house!,내 집이야!,my house|Toad was very proud.,자랑스러워했어요.,proud|It is very big!,매우 커!,big|Come and visit me!,놀러 와!,visit|Welcome to Toad Hall!,환영!,Welcome to","house,하우스,ou는 아우|proud,프라우드,pr 빠르게|visit,비짓,강세 첫째","mom,This is your house?,네 집이야?|kid,My house! It is big!,내 집이야!|mom,Very proud.,자랑스럽겠다.|kid,Come visit!,놀러 와요!"],
["16",4,"05","Wind in the Willows","Kenneth Grahame","1908","Look at my new car!","car,차|new,새로운|fast,빠른|worry,걱정하다","토드가 새 차에 빠져요.","Look at my new car!,새 차 봐!,Look at|It goes very fast!,빨리 가!,goes fast|Toad loved his car.,차를 사랑했어요.,loved|His friends were worried.,걱정했어요.,worried|Be careful Toad!,조심해!,Be careful","car,카r,r 길게|worry,워리,w 둥글게|fast,패스트,a 길게","mom,Look at my car!,차 봐!|kid,So fast!,빨라요!|mom,I am worried.,걱정돼.|kid,I'll be careful!,조심할게요!"],
["17",4,"06","Wind in the Willows","Kenneth Grahame","1908","I am lost!","forest,숲|dark,어두운|snow,눈|lost,길을 잃은","몰이 숲에서 길을 잃어요.","Mole walked into the forest.,숲으로 들어갔어요.,walked into|It was very dark.,어두웠어요.,dark|I am lost!,길 잃었어!,lost|Snow began to fall.,눈이 내려요.,began|He was cold and scared.,춥고 무서웠어요.,cold and scared","forest,포리스트,강세 첫째|dark,다r크,r 부드럽게|lost,로스트,o 짧게","mom,Where are we?,어디지?|kid,I am lost!,길 잃었어요!|mom,Stay with me.,같이 있어.|kid,It's snowing!,눈이 와요!"],
["18",4,"07","Wind in the Willows","Kenneth Grahame","1908","Come in! You are safe here.","safe,안전한|warm,따뜻한|cozy,아늑한|welcome,환영하다","오소리 배저의 따뜻한 집이에요.","Come in! You are safe here.,들어와! 안전해.,Come in|Badger's house was warm.,따뜻했어요.,warm|It was so cozy inside.,아늑했어요.,cozy|Welcome my friends!,환영해!,Welcome|They felt happy and safe.,행복하고 안전했어요.,felt","safe,세이프,f 살짝|cozy,코우지,o는 오우|welcome,웰컴,l 가볍게","mom,Come in! Safe here.,들어와!|kid,So warm!,따뜻해요!|mom,Hot soup?,수프?|kid,Yes! Cozy!,아늑해요!"],
["19",4,"08","Wind in the Willows","Kenneth Grahame","1908","We are best friends!","best,최고의|laugh,웃다|dinner,저녁식사|celebrate,축하하다","친구들이 모여서 축하해요!","We are best friends!,최고의 친구!,best friends|They laughed together.,함께 웃었어요.,laughed|Let's have dinner!,저녁 먹자!,Let's have|They celebrated all night.,밤새 축하했어요.,celebrated|What wonderful friends!,멋진 친구들!,wonderful","laugh,래프,gh는 f|dinner,디너r,nn 하나처럼|celebrate,셀러브레잇,강세 첫째","mom,Best friends!,최고 친구!|kid,I love being friends!,좋아요!|mom,Let's celebrate!,축하하자!|kid,Hooray!,만세!"],
["20",4,"09","Wizard of Oz","L. Frank Baum","1900","Where am I?","tornado,토네이도|land,땅|strange,이상한|welcome,환영하다","도로시가 토네이도에 휩쓸려 낯선 땅에!","A tornado took Dorothy away.,토네이도가 데려갔어요.,took away|Where am I?,여기가 어디지?,Where am I|This is a strange land.,이상한 땅이야.,strange|Welcome to Oz!,오즈에 환영!,Welcome to|Dorothy was confused.,혼란스러웠어요.,confused","tornado,토r네이도,강세 두번째|strange,스트레인지,str 빠르게|welcome,웰컴,l 가볍게","mom,Where are we?,어디지?|kid,Where am I?,어디지?|mom,Welcome to Oz!,환영!|kid,I want to go home!,집에 가고 싶어요!"],
["21",4,"10","Wizard of Oz","L. Frank Baum","1900","I need a brain!","brain,뇌|scarecrow,허수아비|smart,똑똑한|think,생각하다","뇌가 필요한 허수아비를 만나요.","I need a brain!,뇌가 필요해!,need|The Scarecrow could not think.,생각할 수 없었어요.,could not|I want to be smart.,똑똑해지고 싶어.,smart|Come with me!,같이 가자!,Come with me|They walked together.,함께 걸었어요.,together","brain,브레인,br 빠르게|scarecrow,스케어크로우,합성어|smart,스마r트,r 가볍게","mom,What do you need?,필요해?|kid,I need a brain!,뇌요!|mom,Come with me!,같이 가자!|kid,Let's go!,가요!"],
["22",4,"11","Wizard of Oz","L. Frank Baum","1900","I need a heart!","heart,심장|forest,숲|move,움직이다|rusty,녹슨","녹슨 양철 나무꾼을 만나요!","I need a heart!,심장이 필요해!,heart|The Tin Man was rusty.,녹슬어 있었어요.,rusty|He could not move.,움직일 수 없었어요.,could not move|Help me please!,도와줘요!,Help me|They found him in the forest.,숲에서 찾았어요.,found","heart,하r트,ea는 아|rusty,러스티,r 강하게|forest,포리스트,강세 첫째","mom,Who is there?,누구?|kid,Help me!,도와줘요!|mom,What do you need?,필요해?|kid,A heart!,심장이요!"],
["23",4,"12","Wizard of Oz","L. Frank Baum","1900","I need courage!","courage,용기|lion,사자|scared,무서운|brave,용감한","겁쟁이 사자를 만나요!","I need courage!,용기가 필요해!,courage|The lion was always scared.,항상 무서워했어요.,always|I want to be brave!,용감해지고 싶어!,brave|Don't be afraid!,무서워하지 마!,Don't be|We will help each other.,서로 도울 거야.,each other","courage,커리지,강세 첫째|lion,라이언,2음절|brave,브레이브,v 살짝","mom,Are you scared?,무서워?|kid,I need courage!,용기요!|mom,You can be brave!,용감해질 수 있어!|kid,I want to be brave!,용감해지고 싶어요!"],
["24",4,"13","Wizard of Oz","L. Frank Baum","1900","Follow the yellow brick road!","emerald,에메랄드|city,도시|road,길|follow,따라가다","에메랄드 시티로 가는 길!","Follow the yellow brick road!,노란 벽돌 길!,Follow|They walked to Emerald City.,에메랄드 시티로.,walked to|The road was long.,길이 길었어요.,long|They sang along the way.,노래했어요.,along the way|Almost there!,거의 다 왔어!,Almost","emerald,에머럴드,강세 첫째|follow,팔로우,f 가볍게|road,로우드,oa는 오우","mom,Which way?,어느 쪽?|kid,Follow the road!,길을 따라!|mom,How far?,얼마나?|kid,Almost there!,거의 다!"],
["25",4,"14","Wizard of Oz","L. Frank Baum","1900","I will get you!","witch,마녀|broom,빗자루|together,함께|fight,싸우다","마녀가 위협해요!","I will get you!,잡아버릴 거야!,will get|The witch flew on her broom.,빗자루 타고 날았어요.,flew|We are together!,함께야!,together|We will fight!,싸울 거야!,fight|Don't be scared!,무서워하지 마!,Don't be","witch,위치,w 둥글게|broom,브룸,oo 길게|fight,파잇,gh 묵음","mom,The witch is coming!,마녀가 와!|kid,I will get you!,잡을 거야!|mom,Don't be scared!,무서워 마!|kid,We fight together!,함께!"],
["26",4,"15","Wizard of Oz","L. Frank Baum","1900","I'm melting!","water,물|melt,녹다|throw,던지다|defeat,물리치다","도로시가 물로 마녀를 물리쳐요!","Dorothy threw water!,물을 던졌어요!,threw|I'm melting!,녹고 있어!,melting|The witch was defeated.,물리쳐졌어요.,defeated|We did it!,해냈어!,did it|Everyone cheered!,모두 환호!,cheered","melting,멜팅,l 가볍게|throw,쓰로우,th 혀 내밀어|water,워터r,t는 d처럼","mom,Take this water!,물!|kid,I'm melting!,녹고 있어!|mom,We did it!,해냈어!|kid,Hooray!,만세!"],
["27",4,"16","Wizard of Oz","L. Frank Baum","1900","There's no place like home!","home,집|place,장소|wizard,마법사|click,딸깍","집이 가장 좋다는 걸 깨달아요.","There's no place like home!,집만한 곳은 없어!,no place like|The Wizard was not real.,진짜가 아니었어요.,was not real|You had it all along.,처음부터 있었어.,all along|Click your heels three times.,구두 세 번 딸깍.,three times|Dorothy wanted to go home.,집에 가고 싶었어요.,wanted to","wizard,위저드,z는 ㅈ|place,플레이스,pl 빠르게|click,클릭,ck 짧게","mom,What did you learn?,뭘 배웠니?|kid,No place like home!,집이 최고!|mom,Click your heels!,딸깍!|kid,I want to go home!,집에 가고 싶어요!"],
["28",4,"17","Wizard of Oz","L. Frank Baum","1900","You had it all along!","already,이미|always,항상|inside,안에|believe,믿다","뇌 심장 용기는 이미 안에!","You had it all along!,처음부터 있었어!,all along|The brain was already inside.,이미 안에 있었어요.,already|You always had courage.,항상 용기가 있었어.,always|Believe in yourself!,자신을 믿어!,believe in|They were happy.,행복했어요.,were happy","already,올레디,강세 두번째|believe,빌리브,강세 두번째|inside,인사이드,강세 두번째","mom,Did the Wizard help?,도와줬니?|kid,I had it all along!,처음부터!|mom,Believe in yourself!,자신을 믿어!|kid,I always had courage!,항상 있었어요!"],
["29",4,"18","Wizard of Oz","L. Frank Baum","1900","There's no place like home!","click,딸깍|home,집|close,감다|back,돌아가다","도로시가 루비 구두로 집에!","Dorothy clicked her ruby shoes.,루비 구두를 딸깍!,clicked|There's no place like home!,집만한 곳은 없어!,no place like|She closed her eyes.,눈을 감았어요.,closed|She was back in Kansas!,캔자스로!,was back|I'm home!,집이야!,I'm home","click,클릭,ck 짧게|close,클로우즈,z로 끝|Kansas,캔저스,a는 애","mom,Click your shoes!,딸깍!|kid,No place like home!,집이 최고!|mom,Open your eyes!,눈을 떠!|kid,I'm home!,집이야!"],
["30",5,"02","Treasure Island","Robert L. Stevenson","1883","Let's go on an adventure!","adventure,모험|ship,배|sail,항해하다|captain,선장","짐이 보물 지도를 들고 모험을!","Let's go on an adventure!,모험을 떠나자!,Let's go|They sailed on a big ship.,큰 배로 항해!,sailed|The captain led the way.,선장이 이끌었어요.,led|Jim was very excited.,흥분했어요.,excited|The ocean was beautiful.,바다가 아름다웠어요.,ocean","adventure,어드벤처r,강세 두번째|captain,캡틴,ai는 이|sail,세일,ai는 에이","mom,Ready for adventure?,모험 준비?|kid,Let's go!,떠나자!|mom,The ship is waiting!,배가 기다려!|kid,I see the ocean!,바다!"]
];
const gn={3:'초등 3학년',4:'초등 4학년',5:'초등 5학년'};
const gl={3:'A1 ~ A2',4:'A1+ ~ A2+',5:'A2 ~ B1'};
const im={'Peter Rabbit,3':'https://pub-a418b5aad0bd4c3fb41cf7159403fc12.r2.dev/images/peter-rabbit/w{W}_new.png','Wind in the Willows,4':'https://pub-a418b5aad0bd4c3fb41cf7159403fc12.r2.dev/images/wind-willows/w{W}_scene.png','Wizard of Oz,4':'https://pub-a418b5aad0bd4c3fb41cf7159403fc12.r2.dev/camp-a/images/grade4/w{W}_01.png','Treasure Island,5':'https://pub-a418b5aad0bd4c3fb41cf7159403fc12.r2.dev/images/treasure-island/w{W}_scene.png'};
for(const d of D){
const[nn,g,ww,bk,au,yr,ke,wdS,st,seS,prS,roS]=d;
const wds=wdS.split('|').map(x=>{const p=x.split(',');return{en:p[0],kr:p[1]};});
const sns=seS.split('|').map(x=>{const p=x.split(',');return{en:p[0],kr:p[1],tip:p[2]||''};});
const prs=prS.split('|').map(x=>{const p=x.split(',');return{w:p[0],pk:p[1],tip:p[2]||''};});
const ros=roS.split('|').map(x=>{const p=x.split(',');return{r:p[0],en:p[1],kr:p[2]||''};});
const img=(im[bk+','+g]||'https://pub-a418b5aad0bd4c3fb41cf7159403fc12.r2.dev/images/robo/robo.png').replace('{W}',ww);
const pn=parseInt(nn);
const pv=pn>1?`<a href="ep${String(pn-1).padStart(2,'0')}.html">\u2190 EP${String(pn-1).padStart(2,'0')}</a>`:'<a href="/mom-teacher/">목록</a>';
const nx=pn<30?`<a href="ep${String(pn+1).padStart(2,'0')}.html">EP${String(pn+1).padStart(2,'0')} \u2192</a>`:'<span style="opacity:0.3;">준비 중</span>';
const sh=sns.map(s=>`<div class="sent"><button class="sent-play" onclick="speak('${s.en.replace(/'/g,"\\'")}')">&#9654;</button><div class="sent-text"><div class="sent-en">${s.en}</div><div class="sent-kr">${s.kr}</div><div class="sent-tip">${s.tip}</div></div></div>`).join('\n');
const ph=prs.map(p=>`<div class="sent" style="border-color:rgba(143,175,143,0.2);"><button class="sent-play" style="background:var(--sage);" onclick="speak('${p.w}')">&#9654;</button><div class="sent-text"><div class="sent-en" style="font-size:1.3rem;">${p.w}</div><div class="sent-kr"><strong>${p.pk}</strong> &middot; ${p.tip}</div></div></div>`).join('\n');
const rh=ros.map(r=>{const c=r.r==='mom'?'mom':'kid';const l=r.r==='mom'?'MOTHER (엄마)':'CHILD (아이)';return`<div class="role"><div class="role-label role-${c}">${l}</div><div class="role-line role-line-${c}">"${r.en}"<div class="role-kr">${r.kr}</div></div></div>`;}).join('\n');
const wh=wds.map(x=>`<span style="background:white;padding:4px 12px;border-radius:8px;font-size:0.82rem;font-weight:700;">${x.en} <span style="color:var(--brown-muted);">${x.kr}</span></span>`).join(' ');
const aiS=sns.map(s=>'- '+s.en).join('\\n');
const h=`<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>EP${nn} ${bk} \u2014 엄마 영어 선생님 | CEC</title><link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;0,900;1,400&family=Noto+Sans+KR:wght@300;400;500;700;900&display=swap" rel="stylesheet"><style>${CSS}</style></head><body>
<nav class="nav"><a class="nav-brand" href="/mom-teacher/"><span>Mom</span> Teacher</a><ul class="nav-links"><li><a href="/mom-teacher/">Home</a></li><li><a href="/mom-teacher/ep${nn}.html" class="active">EP${nn}</a></li><li><a href="/">CEC Main</a></li></ul></nav>
<div class="wrap">
<section class="ep-hero"><div class="ep-hero-img"><img src="${img}" alt="${bk}"></div><div class="ep-hero-text"><div class="ep-eyebrow">EPISODE ${nn}</div><h1 class="ep-title">${bk}</h1><div class="ep-author">${au}, ${yr}</div><div class="ep-desc">${st}</div><div class="ep-tags"><span class="ep-tag tag-grade">${gn[g]} 연계</span><span class="ep-tag tag-level">${gl[g]} Level</span></div></div></section>
<div class="card"><div class="card-hdr"><div class="card-num" style="background:var(--sage);">1</div><div><div class="card-title">아이 수업 미리보기</div><div class="card-sub">이번 주 배울 내용</div></div></div><div class="card-body"><a href="/camp-a/lessons/grade${g}/week${ww}.html" target="_blank" style="display:block;padding:24px;background:linear-gradient(135deg,#faf8f4,var(--sage-light));border-radius:16px;text-decoration:none;color:var(--brown);border:1.5px solid rgba(143,175,143,0.2);"><div style="font-size:0.65rem;font-weight:800;color:var(--sage-dark);letter-spacing:2px;margin-bottom:8px;">GRADE ${g} &middot; WEEK ${ww}</div><div style="font-family:'Playfair Display',serif;font-size:1.2rem;font-weight:700;margin-bottom:10px;">${bk}</div><div style="display:flex;gap:12px;flex-wrap:wrap;margin-bottom:12px;"><div style="background:white;padding:8px 14px;border-radius:10px;font-size:0.82rem;font-weight:700;border:1px solid rgba(196,149,106,0.15);"><span style="color:var(--rose);">핵심 표현</span><br>${ke}</div><div style="background:white;padding:8px 14px;border-radius:10px;font-size:0.82rem;font-weight:700;border:1px solid rgba(196,149,106,0.15);"><span style="color:var(--sage-dark);">단어 4개</span><br>${wds.map(x=>x.en).join(', ')}</div></div><div style="font-size:0.82rem;font-weight:700;color:var(--sage-dark);">아이 수업 미리보기 &rarr;</div></a></div></div>
<div class="card"><div class="card-hdr"><div class="card-num" style="background:var(--rose);">2</div><div><div class="card-title">이것만 준비하면 돼요</div><div class="card-sub">핵심 3가지</div></div></div><div class="card-body"><div style="display:grid;gap:14px;"><div style="background:var(--rose-light);border-radius:14px;padding:18px;border-left:4px solid var(--rose);"><div style="font-size:0.65rem;font-weight:800;color:var(--rose);letter-spacing:2px;margin-bottom:6px;">POINT 1</div><div style="font-family:'Playfair Display',serif;font-size:1rem;font-weight:700;color:var(--brown);margin-bottom:4px;">핵심 문장</div><div style="font-family:'Playfair Display',serif;font-size:1.2rem;font-weight:700;color:var(--rose);font-style:italic;">"${ke}"</div></div><div style="background:var(--sage-light);border-radius:14px;padding:18px;border-left:4px solid var(--sage);"><div style="font-size:0.65rem;font-weight:800;color:var(--sage-dark);letter-spacing:2px;margin-bottom:6px;">POINT 2</div><div style="font-family:'Playfair Display',serif;font-size:1rem;font-weight:700;color:var(--brown);margin-bottom:6px;">단어 4개</div><div style="display:flex;gap:8px;flex-wrap:wrap;">${wh}</div></div><div style="background:linear-gradient(135deg,#faf8f4,#fff);border-radius:14px;padding:18px;border-left:4px solid var(--brown);border:1.5px solid rgba(196,149,106,0.1);"><div style="font-size:0.65rem;font-weight:800;color:var(--brown-light);letter-spacing:2px;margin-bottom:6px;">POINT 3</div><div style="font-family:'Playfair Display',serif;font-size:1rem;font-weight:700;color:var(--brown);margin-bottom:6px;">줄거리</div><div style="font-size:0.85rem;color:var(--brown-light);line-height:1.8;">${st}</div></div></div></div></div>
<div class="card"><div class="card-hdr"><div class="card-num" style="background:var(--rose);">3</div><div><div class="card-title">소리내어 읽어봐요</div><div class="card-sub">5개 문장 듣고 따라 읽기</div></div></div><div class="card-body">${sh}</div></div>
<div class="card"><div class="card-hdr"><div class="card-num" style="background:var(--sage);">4</div><div><div class="card-title">발음 포인트</div><div class="card-sub">주의할 발음</div></div></div><div class="card-body">${ph}</div></div>
<div class="card"><div class="card-hdr"><div class="card-num" style="background:var(--brown);">5</div><div><div class="card-title">집에서 하는 역할극</div><div class="card-sub">엄마+아이 대화</div></div></div><div class="card-body">${rh}<div style="font-size:0.78rem;color:var(--brown-muted);margin-top:12px;padding:12px;background:var(--cream);border-radius:10px;">Tip: 엄마가 상황 설명, 아이가 주인공 역할</div></div></div>
<div class="card"><div class="card-hdr"><div class="card-num" style="background:var(--rose);">6</div><div><div class="card-title">5일 연습 플랜</div><div class="card-sub">하루 10분</div></div></div><div class="card-body"><div class="plan-grid"><div class="plan-day"><div class="plan-d">DAY 1</div><div class="plan-task">문장 5개<br>듣기</div></div><div class="plan-day"><div class="plan-d">DAY 2</div><div class="plan-task">따라<br>읽기</div></div><div class="plan-day"><div class="plan-d">DAY 3</div><div class="plan-task">발음<br>연습</div></div><div class="plan-day"><div class="plan-d">DAY 4</div><div class="plan-task">역할극<br>연습</div></div><div class="plan-day"><div class="plan-d">DAY 5</div><div class="plan-task">아이에게<br>읽어주기</div></div></div></div></div>
<div class="card"><div class="card-hdr"><div class="card-num" style="background:linear-gradient(135deg,var(--rose),var(--sage));">7</div><div><div class="card-title">AI와 연습하기</div><div class="card-sub">ChatGPT로 발음 연습</div></div></div><div class="card-body"><div class="ai-card"><div class="ai-title">ChatGPT와 영어 대화 연습</div><div class="ai-desc">버튼을 누르면 대화 내용이 복사됩니다.</div><button class="ai-btn" onclick="openAI()">ChatGPT와 연습하기 &rarr;</button></div></div></div>
<nav class="ep-nav">${pv}${nx}</nav>
</div>
<script>
${BASE_SCRIPT}
function openAI(){var p="${gn[g]} 자녀 엄마입니다. ${bk} 읽어주기 연습 중.\\n문장:\\n${aiS}\\n발음 교정과 감정 넣는 법 알려주세요.";navigator.clipboard.writeText(p);setTimeout(function(){window.open('https://chatgpt.com/g/g-69b48918e32c81919f5a6c6c6d187df3-yeongeo-tyuteo-cec-englishcamp-c');},300);}
</script></body></html>`;
fs.writeFileSync(__dirname+'/ep'+nn+'.html',h,'utf8');
console.log('ep'+nn+'.html G'+g+'W'+ww+' '+bk);
}
console.log('Done! 26 files.');
