var GRAMMAR_STORY_MAP = {
  "G01":{"title":"Be동사 현재형","level":"A1","example":"Peter is a naughty little rabbit.","prompt":"저는 G01 Be동사를 공부 중이에요. am/is/are 사용법을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G02":{"title":"관사 a/an/the","level":"A1","example":"There was a garden. The garden belonged to Mr. McGregor.","prompt":"저는 G02 관사를 공부 중이에요. a/an/the 차이를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G03":{"title":"단순현재시제","level":"A1","example":"Peter runs into the garden every day.","prompt":"저는 G03 단순현재를 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G04":{"title":"현재진행형","level":"A1","example":"Peter is running away!","prompt":"저는 G04 현재진행형을 공부 중이에요. am/is/are+-ing를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G05":{"title":"단순과거시제","level":"A1","example":"Peter ate vegetables and ran away.","prompt":"저는 G05 단순과거를 공부 중이에요. 규칙/불규칙 과거형을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G06":{"title":"미래시제 will/going to","level":"A1","example":"I am going to study English today.","prompt":"저는 G06 미래시제를 공부 중이에요. will과 going to 차이를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G07":{"title":"조동사 can/must","level":"A1","example":"I can speak English. You must study hard.","prompt":"저는 G07 조동사를 공부 중이에요. can/must/should를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G08":{"title":"셀 수 있는/없는 명사","level":"A1","example":"I need some water and two apples.","prompt":"저는 G08 가산/불가산 명사를 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G09":{"title":"의문문 만들기","level":"A1","example":"Where do you live? What did you eat?","prompt":"저는 G09 의문문을 공부 중이에요. wh-의문문을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G10":{"title":"비교급/최상급","level":"A1","example":"She is taller than me. He is the tallest.","prompt":"저는 G10 비교급/최상급을 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G11":{"title":"소유격 표현","level":"A1","example":"This is my book. That is John's bag.","prompt":"저는 G11 소유격을 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G12":{"title":"There is/There are","level":"A1","example":"There is a cat. There are many students.","prompt":"저는 G12 There is/are를 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G13":{"title":"장소 전치사","level":"A1","example":"The book is on the table. She is in the room.","prompt":"저는 G13 장소 전치사를 공부 중이에요. in/on/at/under를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G14":{"title":"시간 전치사","level":"A1","example":"I study at 8. She was born in May.","prompt":"저는 G14 시간 전치사를 공부 중이에요. in/on/at 시간 용법을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G15":{"title":"지시대명사","level":"A1","example":"This is mine. Those are yours.","prompt":"저는 G15 지시대명사를 공부 중이에요. this/that/these/those를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G16":{"title":"명령문","level":"A1","example":"Open the door! Don't be late!","prompt":"저는 G16 명령문을 공부 중이에요. 긍정/부정 명령문을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G17":{"title":"빈도부사","level":"A1","example":"I always eat breakfast. She never drinks coffee.","prompt":"저는 G17 빈도부사를 공부 중이에요. always/often/sometimes/never 위치를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G18":{"title":"형용사","level":"A1","example":"She is a kind teacher. The sky is blue.","prompt":"저는 G18 형용사를 공부 중이에요. 위치와 사용법을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G19":{"title":"접속사 and/but/or/so","level":"A1","example":"I like tea but she likes coffee.","prompt":"저는 G19 접속사를 공부 중이에요. and/but/or/so를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G20":{"title":"조동사 should/may","level":"A1","example":"You should sleep early. May I help you?","prompt":"저는 G20 조동사를 공부 중이에요. should/may/might를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G21":{"title":"과거진행형","level":"A2","example":"I was reading when she called.","prompt":"저는 G21 과거진행형을 공부 중이에요. was/were+-ing를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G22":{"title":"현재완료","level":"A2","example":"I have lived here for 10 years.","prompt":"저는 G22 현재완료를 공부 중이에요. have/has+p.p.를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G23":{"title":"수동태","level":"A2","example":"The letter was written by Jane.","prompt":"저는 G23 수동태를 공부 중이에요. be+p.p. 구조를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G24":{"title":"간접의문문","level":"A2","example":"I wonder where he lives.","prompt":"저는 G24 간접의문문을 공부 중이에요. 어순 변화를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G25":{"title":"관계대명사","level":"A2","example":"The man who helped me is my teacher.","prompt":"저는 G25 관계대명사를 공부 중이에요. who/which/that을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G26":{"title":"동명사/부정사","level":"A2","example":"I enjoy reading. She decided to leave.","prompt":"저는 G26 동명사/부정사를 공부 중이에요. 차이점을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G27":{"title":"가정법 과거","level":"A2","example":"If I were rich, I would travel.","prompt":"저는 G27 가정법 과거를 공부 중이에요. If+과거,would+동사원형을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G28":{"title":"분사구문","level":"A2","example":"Sitting alone, she felt lonely.","prompt":"저는 G28 분사구문을 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G29":{"title":"시간 접속사","level":"A2","example":"Before she left, she called him.","prompt":"저는 G29 시간 접속사를 공부 중이에요. when/while/before/after를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G30":{"title":"too/enough","level":"A2","example":"It is too hot. She is old enough.","prompt":"저는 G30 too/enough를 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G31":{"title":"현재완료진행형","level":"A2","example":"She has been waiting for an hour.","prompt":"저는 G31 현재완료진행형을 공부 중이에요. have been+-ing를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G32":{"title":"used to","level":"A2","example":"I used to live in Busan.","prompt":"저는 G32 used to를 공부 중이에요. 과거 습관 표현을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G33":{"title":"wish 가정법","level":"A2","example":"I wish I could fly.","prompt":"저는 G33 wish 가정법을 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G34":{"title":"so/such","level":"A2","example":"It was such a great movie. She is so kind.","prompt":"저는 G34 so/such를 공부 중이에요. 차이점을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G35":{"title":"재귀대명사","level":"A2","example":"He hurt himself. She did it herself.","prompt":"저는 G35 재귀대명사를 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G36":{"title":"조동사 과거형","level":"A2","example":"She could swim when she was young.","prompt":"저는 G36 조동사 과거형을 공부 중이에요. could/would/might를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G37":{"title":"부정대명사","level":"A2","example":"Some students passed. No one failed.","prompt":"저는 G37 부정대명사를 공부 중이에요. some/any/no를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G38":{"title":"It takes/costs","level":"A2","example":"It takes 30 minutes to get there.","prompt":"저는 G38 It takes를 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G39":{"title":"have something done","level":"A2","example":"I had my hair cut yesterday.","prompt":"저는 G39 have+목적어+p.p.를 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G40":{"title":"직접/간접화법","level":"A2","example":"She said she was tired.","prompt":"저는 G40 화법을 공부 중이에요. 직접→간접 변환을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G41":{"title":"과거완료","level":"A2","example":"She had left before I arrived.","prompt":"저는 G41 과거완료를 공부 중이에요. had+p.p.를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G42":{"title":"1형식 조건문","level":"A2","example":"If it rains, I will stay home.","prompt":"저는 G42 1형식 조건문을 공부 중이에요. If+현재,will+동사원형을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G43":{"title":"2형식 조건문","level":"B1","example":"If I were you, I would study more.","prompt":"저는 G43 2형식 조건문을 공부 중이에요. If+과거,would를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G44":{"title":"분사형용사","level":"B1","example":"The movie was boring. I was bored.","prompt":"저는 G44 분사형용사를 공부 중이에요. -ing/-ed 차이를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G45":{"title":"관계부사","level":"B1","example":"This is the place where I was born.","prompt":"저는 G45 관계부사를 공부 중이에요. where/when/why를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G46":{"title":"부정사 의미상 주어","level":"B1","example":"It is hard for me to understand.","prompt":"저는 G46 부정사 의미상 주어를 공부 중이에요. for+목적어+to를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G47":{"title":"강조구문 It is~that","level":"B1","example":"It was Mary that called me.","prompt":"저는 G47 강조구문을 공부 중이에요. It is/was~that을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G48":{"title":"복합관계사","level":"B1","example":"Whoever comes is welcome.","prompt":"저는 G48 복합관계사를 공부 중이에요. whoever/whatever를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G49":{"title":"도치구문","level":"B1","example":"Never have I seen such beauty.","prompt":"저는 G49 도치구문을 공부 중이에요. 부정어 도치를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G50":{"title":"동명사/부정사 의미차이","level":"B1","example":"I stopped smoking. I stopped to smoke.","prompt":"저는 G50 동명사/부정사 의미차이를 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G51":{"title":"수동태 심화","level":"B1","example":"English is spoken worldwide.","prompt":"저는 G51 수동태 심화를 공부 중이에요. 다양한 시제 수동태를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G52":{"title":"가정법 3형식","level":"B1","example":"If she had studied, she would have passed.","prompt":"저는 G52 가정법 3형식을 공부 중이에요. If+had p.p.,would have p.p.를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G53":{"title":"명사절","level":"B1","example":"I know that she is right.","prompt":"저는 G53 명사절을 공부 중이에요. that/whether/if 명사절을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G54":{"title":"완료부정사","level":"B1","example":"She seems to have known the truth.","prompt":"저는 G54 완료부정사를 공부 중이에요. to have+p.p.를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G55":{"title":"양보 접속사","level":"B1","example":"Although it rained, we went out.","prompt":"저는 G55 양보접속사를 공부 중이에요. although/even though를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G56":{"title":"원급 비교 as~as","level":"B1","example":"She runs as fast as a cheetah.","prompt":"저는 G56 원급비교를 공부 중이에요. as+형용사+as를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G57":{"title":"so~that","level":"B1","example":"She was so tired that she slept early.","prompt":"저는 G57 so~that을 공부 중이에요. 결과절 구조를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G58":{"title":"사역동사","level":"B1","example":"She made him clean the room.","prompt":"저는 G58 사역동사를 공부 중이에요. make/let/have를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G59":{"title":"지각동사","level":"B1","example":"I saw him running in the park.","prompt":"저는 G59 지각동사를 공부 중이에요. see/hear/feel+목적어+-ing를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G60":{"title":"혼합가정법","level":"B1","example":"If I had studied, I would be rich now.","prompt":"저는 G60 혼합가정법을 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G61":{"title":"관계대명사 what","level":"B1","example":"What she said surprised me.","prompt":"저는 G61 관계대명사 what을 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G62":{"title":"이유 부사절","level":"B1","example":"Since it was late, I went home.","prompt":"저는 G62 이유부사절을 공부 중이에요. because/since/as를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G63":{"title":"with 독립분사구문","level":"B1","example":"With eyes closed, she listened.","prompt":"저는 G63 with 독립분사를 공부 중이에요. with+명사+분사를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G64":{"title":"명사구 후치수식","level":"B1","example":"The man standing there is my father.","prompt":"저는 G64 후치수식을 공부 중이에요. 분사/형용사구 수식을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G65":{"title":"간접의문문 심화","level":"B1","example":"Do you know where she has gone?","prompt":"저는 G65 간접의문문 심화를 공부 중이에요. 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G66":{"title":"수량형용사","level":"B1","example":"Few students passed. Much work remains.","prompt":"저는 G66 수량형용사를 공부 중이에요. few/little/many/much를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G67":{"title":"접속부사","level":"B1","example":"However, she kept trying.","prompt":"저는 G67 접속부사를 공부 중이에요. however/therefore/moreover를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G68":{"title":"비교급 강조","level":"B1","example":"She is much taller than before.","prompt":"저는 G68 비교급 강조를 공부 중이에요. much/far/even+비교급을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G69":{"title":"원형부정사","level":"B1","example":"She helped me carry the bags.","prompt":"저는 G69 원형부정사를 공부 중이에요. help/let/make 다음 원형을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G70":{"title":"추측 조동사","level":"B1","example":"He must be tired. She might be wrong.","prompt":"저는 G70 추측 조동사를 공부 중이에요. must/might/can't를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G71":{"title":"과거추측 조동사","level":"B1","example":"She must have forgotten.","prompt":"저는 G71 과거추측을 공부 중이에요. must have/can't have+p.p.를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G72":{"title":"관계대명사 계속적 용법","level":"B1","example":"She passed, which surprised us.","prompt":"저는 G72 관계대명사 계속적 용법을 공부 중이에요. ,which/,who를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G73":{"title":"부정사 형용사적 용법","level":"B1","example":"I have work to do.","prompt":"저는 G73 부정사 형용사적 용법을 공부 중이에요. 명사수식 to부정사를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G74":{"title":"양보 부사절 as/though","level":"B1","example":"Hard as he tried, he failed.","prompt":"저는 G74 양보부사절을 공부 중이에요. 형용사+as/though 도치를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G75":{"title":"강조 do/does/did","level":"B1","example":"I do believe you.","prompt":"저는 G75 강조 do를 공부 중이에요. do/does/did 강조용법을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G76":{"title":"분열문","level":"B1","example":"It was John that broke the window.","prompt":"저는 G76 분열문을 공부 중이에요. It is/was~that 분열문을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G77":{"title":"not~until","level":"B1","example":"It was not until noon that she woke.","prompt":"저는 G77 not~until을 공부 중이에요. 강조구조를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G78":{"title":"문장 연결어","level":"B1","example":"As a result, sales increased.","prompt":"저는 G78 문장연결어를 공부 중이에요. as a result/in contrast 등을 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G79":{"title":"수일치 심화","level":"B1","example":"Each of the students has a book.","prompt":"저는 G79 수일치를 공부 중이에요. each/every/neither+단수를 예문 3개와 연습문제 2개로 설명해주세요!"},
  "G80":{"title":"고급 문법 패턴","level":"B1","example":"Had I known, I would have helped.","prompt":"저는 G80 고급문법을 공부 중이에요. if생략 도치가정법을 예문 3개와 연습문제 2개로 설명해주세요!"}
};
