name = "cec-register"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "cec_registrations"
database_name = "cec-registrations"
database_id = "9fd8ea1c-ea9b-49c0-a37d-adc5bc04d018"
